### ISSUE TITLE
opencv_4.2.0.imx.bb corrupted by meta-imx-patch

### ISSUE THREAD

**Issue by bkardosa** [ArrowElectronics/I.IMX8X_AI_ML#1]
Commit 61144251 in meta-imx fixes "SRCREV_opencv" in opencv_4.2.0.imx.bb . meta-imx-patch undoes this fix making it impossible to build either "opencv" or "imx-image-full"

**Comment by Darsh-Dev** [comment]
Thanks @bkardosa 

Resolved the [opencv fetch issue](https://github.com/ArrowElectronics/I.IMX8X_AI_ML/commit/511c646d421499e8b1ff3f3d3b9a1c1b4caa3875) in both AIML and Thor96.
